Citizens API Integration
EnocraftMC/UltraCosmetics pull request #1
Opened 2020-04-25 23:04 UTC by cxbrettbaker

2020-04-26 01:07 UTC, Hk-tang requested changes
Made some comments. Light changes, I didn't see anything that **really** needed to change

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/UltraCosmetics.java
> -            //config.set("Auto-Equip-Cosmetics.on-join", true);
Should remove commented out code

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/CommandShowcaseManager.java
> +			from = 8 * (page - 1) + 1;
Why do we need to multiple by 8? Just adding a comment is sufficient

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/CommandShowcaseManager.java
> +		for (int h = from; h <= to; h++) {
what is variable `h` supposed to be?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/CommandShowcaseManager.java
> +		int h = (int) Math.floor(j * 100) / 100;
Comments explaining the logic behind the calculations is needed

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/CommandShowcaseManager.java
> +	public boolean onCommand(CommandSender sender, Command command, String label, String[] arguments) {
Comments needed explaining what this is doing. Why are we returning a boolean onCommand?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/UCTabCompleter.java
> +            switch(args.length) {
What is case 1, 2, 3, etc.? Like what does it mean when it is case 1/2/3 etc.?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandShowcaseClear.java
> +    public boolean onCommand(CommandSender commandSender, String... args) {
Does onCommand need to return a boolean? or can it just be void? This is for all onCommand in each file if the boolean return type is not used

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandShowcaseClear.java
> +        if (s.startsWith("g")) up.removeGadget();
Instead of just checking if it startsWith can we not do an exact match with `==`?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandToggle.java
> +import org.bukkit.entity.EntityType;
Remove unused import

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/Cosmetic.java
> +        if (owner == null) {
Why do we remove this check?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffect.java
> +            if (Bukkit.getEntity(getOwnerUniqueId()) != null
Do we need to cast to a Player object?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/Pet.java
> +import org.bukkit.scheduler.BukkitRunnable;
Remove unused imports

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/Pet.java
> +            if (Bukkit.getEntity(getOwnerUniqueId()) != null
Do we need to cast to Player object?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/player/UltraPlayerManager.java
> -            cp.clear();
Why do we no longer need to clear?

2020-04-26 01:07 UTC, Hk-tang commented on core/src/main/java/be/isach/ultracosmetics/player/profile/CosmeticsProfile.java
> +        if (enabledGadget != null
should check isEnabled before getCategory.isEnabled since Java evaluates left to right

2020-04-27 04:00 UTC, Hk-tang approved these changes

2020-04-27 15:18 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/player/UltraPlayerManager.java
> -            cp.clear();
Good catch, changed to use clearWithoutSaving()

2020-04-27 15:19 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/Pet.java
> +            if (Bukkit.getEntity(getOwnerUniqueId()) != null
NPCs aren't found with getPlayer

2020-04-27 15:19 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandShowcaseClear.java
> +    public boolean onCommand(CommandSender commandSender, String... args) {
Must return a boolean.

2020-04-27 15:20 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/UltraCosmetics.java
> -            //config.set("Auto-Equip-Cosmetics.on-join", true);
Fixed

2020-04-27 15:23 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/command/CommandShowcaseManager.java
> +			from = 8 * (page - 1) + 1;
This was identical to the code in CommandManager.java, not mine. I'll be refactoring how that whole command works in the future anyways.

2020-04-27 15:25 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/command/CommandShowcaseManager.java
> +	public boolean onCommand(CommandSender sender, Command command, String label, String[] arguments) {
onCommand returns boolean by default. It follows the CommandExecutor interface.

2020-04-27 15:26 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/command/UCTabCompleter.java
> +            switch(args.length) {
case 1 means args.length = 1, will be refactoring this in the next update.

2020-04-27 15:27 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandShowcaseClear.java
> +        if (s.startsWith("g")) up.removeGadget();
Yes. This was the previous author's implementation, untouched. Will be fixing this, presumably it's so you don't have to type the entire string out in-game, just the first couple of characters suffice.

2020-04-27 15:28 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandToggle.java
> +import org.bukkit.entity.EntityType;
Fixed

2020-04-27 15:29 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/Cosmetic.java
> +        if (owner == null) {
To generalize for NPCs

2020-04-27 15:30 UTC, cxbrettbaker commented on core/src/main/java/be/isach/ultracosmetics/cosmetics/particleeffects/ParticleEffect.java
> +            if (Bukkit.getEntity(getOwnerUniqueId()) != null
NPCs are not players

2020-04-27 16:03 UTC, forgeno approved these changes

2020-04-27 16:08 UTC, merged